#!/usr/bin/env bash
#
# Script: entrypoint.sh
# Description: Apply the private-server config overlay, wire NAT address
#              translation for the w3route port, then run bnetd in the
#              foreground for a private Warcraft III: The Frozen Throne realm.
# Usage: entrypoint.sh [extra bnetd args...]
#

set -euo pipefail

# =============================================================================
# CONFIGURATION
# =============================================================================

readonly PVPGN_PREFIX="/usr/local/pvpgn"
readonly BNETD_BIN="${PVPGN_PREFIX}/sbin/bnetd"
readonly OVERRIDES_FILE="${PVPGN_PREFIX}/etc/pvpgn/bnetd.conf.overrides"

# w3route port the WC3 clients reach for matchmaking (must match w3routeaddr).
readonly W3ROUTE_PORT="${PVPGN_W3ROUTE_PORT:-6200}"

# Public IP for NAT address translation. Empty = no translation (LAN/direct).
PVPGN_PUBLIC_IP="${PVPGN_PUBLIC_IP:-}"

# Comma-separated client networks that keep the internal (untranslated) w3route
# address. Defaults to the RFC1918 ranges so only genuinely external clients
# receive the public IP.
PVPGN_LOCAL_CIDR="${PVPGN_LOCAL_CIDR:-192.168.0.0/16,10.0.0.0/8,172.16.0.0/12}"

# Send the bnetd log to stdout (container console). false logs to
# ${LOCALSTATEDIR}/bnetd.log instead.
PVPGN_LOG_STDOUT="${PVPGN_LOG_STDOUT:-true}"

# =============================================================================
# FUNCTIONS
# =============================================================================

log() { printf '[entrypoint] %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

# Locate the installed bnetd.conf. bnetd expands ${SYSCONFDIR}/${LOCALSTATEDIR}
# itself, so we only need the concrete file to patch keys and to place the
# transfile it references.
find_conf() {
    local conf="${PVPGN_PREFIX}/etc/pvpgn/bnetd.conf"
    [[ -f "${conf}" ]] || conf="$(find "${PVPGN_PREFIX}" -type f -name bnetd.conf | head -n1)"
    [[ -n "${conf}" && -f "${conf}" ]] || die "bnetd.conf not found under ${PVPGN_PREFIX}"
    printf '%s' "${conf}"
}

# Idempotently set "key = value" in a pvpgn config file: replace the first
# matching (possibly commented) line, else append.
set_conf_key() {
    local file="$1" key="$2" value="$3"
    local line="${key} = ${value}"
    # shortcut: SOH delimiter keeps ':' '/' '"' in values sed-safe; swap to a
    # temp-file rewrite only if a value ever needs a literal SOH byte.
    local d=$'\001'
    if grep -Eq "^[#[:space:]]*${key}[[:space:]]*=" "${file}"; then
        sed -i "s${d}^[#[:space:]]*${key}[[:space:]]*=.*${d}${line}${d}" "${file}"
    else
        printf '%s\n' "${line}" >> "${file}"
    fi
}

# Apply every "key = value" line from the overrides overlay into bnetd.conf.
apply_overrides() {
    local conf="$1"
    [[ -f "${OVERRIDES_FILE}" ]] || { log "no overrides file, keeping upstream defaults"; return; }
    local raw key value
    while IFS= read -r raw || [[ -n "${raw}" ]]; do
        raw="${raw%%#*}"                                # strip comments
        [[ "${raw}" =~ [^[:space:]] ]] || continue      # skip blank lines
        [[ "${raw}" == *"="* ]] || continue             # skip non key=value
        key="${raw%%=*}"
        key="$(printf '%s' "${key}" | tr -d '[:space:]')"
        value="${raw#*=}"
        value="${value#"${value%%[![:space:]]*}"}"      # ltrim
        value="${value%"${value##*[![:space:]]}"}"      # rtrim
        [[ -n "${key}" ]] || continue
        set_conf_key "${conf}" "${key}" "${value}"
        log "set ${key} = ${value}"
    done < "${OVERRIDES_FILE}"
}

# Point bnetd's transfile at a generated NAT mapping so remote clients receive
# the public IP for the w3route port while LAN clients keep the internal one.
configure_nat() {
    local conf="$1"
    local transfile="${PVPGN_PREFIX}/etc/pvpgn/address_translation.conf"

    if [[ -z "${PVPGN_PUBLIC_IP}" ]]; then
        log "PVPGN_PUBLIC_IP unset, no NAT translation (LAN/direct only)"
        return
    fi

    log "NAT: w3route 0.0.0.0:${W3ROUTE_PORT} -> ${PVPGN_PUBLIC_IP}:${W3ROUTE_PORT}"
    {
        printf '# generated by entrypoint.sh, do not edit by hand\n'
        printf '# input(ip:port)     output(ip:port)     exclude(net)     include(net)\n'
        local cidr
        local -a cidrs
        IFS=',' read -ra cidrs <<< "${PVPGN_LOCAL_CIDR}"
        for cidr in "${cidrs[@]}"; do
            cidr="$(printf '%s' "${cidr}" | tr -d '[:space:]')"
            [[ -n "${cidr}" ]] || continue
            printf '0.0.0.0:%s     %s:%s     %s     ANY\n' \
                "${W3ROUTE_PORT}" "${PVPGN_PUBLIC_IP}" "${W3ROUTE_PORT}" "${cidr}"
        done
    } > "${transfile}"

    set_conf_key "${conf}" "transfile" "\"${transfile}\""
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    [[ -x "${BNETD_BIN}" ]] || die "bnetd binary not found/executable at ${BNETD_BIN}"

    local conf
    conf="$(find_conf)"
    log "using config ${conf}"

    apply_overrides "${conf}"

    if [[ "${PVPGN_LOG_STDOUT}" == "true" ]]; then
        set_conf_key "${conf}" "logfile" "\"/dev/stdout\""
        log "logging to stdout"
    fi

    configure_nat "${conf}"

    # Plain-file account store lives under var/pvpgn; make sure the dirs exist
    # (a mounted volume may start empty). var must be writable by this user.
    mkdir -p "${PVPGN_PREFIX}/var/pvpgn/users" \
             "${PVPGN_PREFIX}/var/pvpgn/clans" \
             "${PVPGN_PREFIX}/var/pvpgn/teams" 2>/dev/null \
        || log "warn: could not create var dirs (check mounted volume perms for uid 1000)"

    log "starting bnetd in foreground (-f)"
    # -f = do not daemonize, -c = explicit config path. exec so bnetd becomes
    # PID 1 and receives container signals directly.
    exec "${BNETD_BIN}" -f -c "${conf}" "$@"
}

main "$@"
